"use client";
import { useState } from "react";
import { Check, Copy, Link2, Send, ShieldCheck } from "lucide-react";

export function AgentConnection({ agentId, agentName }: { agentId: string; agentName: string }) {
  const [host, setHost] = useState("codex"); const [token, setToken] = useState<string>(); const [error, setError] = useState<string>(); const [notice, setNotice] = useState<string>(); const [message, setMessage] = useState(""); const [busy, setBusy] = useState(false);
  const endpoint = typeof window === "undefined" ? "https://callyouragent.vercel.app/mcp" : `${window.location.origin}/mcp`;
  const config = token ? JSON.stringify({ mcpServers: { callyouragent: { url: endpoint, headers: { Authorization: `Bearer ${token}` } } } }, null, 2) : "Create a connection to reveal this private configuration.";
  async function connect() { setBusy(true); setError(undefined); setNotice(undefined); const r = await fetch(`/api/agents/${agentId}/connection`, { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ host }) }); const body = await r.json(); setBusy(false); if (!r.ok) { setError(body.error || "Could not create connection."); return; } setToken(body.token); setNotice("Connection created. Copy it now; this token is only shown once."); }
  async function disconnect() { setBusy(true); const r = await fetch(`/api/agents/${agentId}/connection`, { method: "DELETE" }); setBusy(false); if (!r.ok) { setError("Could not revoke connection."); return; } setToken(undefined); setNotice("Connection revoked. The previous token can no longer make calls."); }
  async function send() { if (!message.trim()) return; setBusy(true); setError(undefined); const r=await fetch(`/api/agents/${agentId}/messages`,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({body:message})}); const body=await r.json();setBusy(false);if(!r.ok){setError(body.error||"Could not send update.");return;}setMessage("");setNotice("Update queued. Your agent receives it the next time it calls pull_human_updates."); }
  return <section className="panel connection-panel"><div className="section-heading"><div><h2>Connect an external agent</h2><p>One private connection for {agentName}. CALL-E credits stay on your account.</p></div><Link2 size={18}/></div><div className="connection-body"><label>Where will you use this agent?<select value={host} onChange={e=>setHost(e.target.value)}><option value="codex">Codex / Codex CLI</option><option value="claude-code">Claude Code</option><option value="gemini-cli">Gemini CLI</option><option value="kiro">Kiro</option><option value="generic">Another MCP client</option></select></label><p className="form-hint">Add the generated remote MCP configuration in your client’s MCP settings. Then tell the agent to use <code>request_phone_call</code> only when a human answer or action is genuinely needed, and <code>pull_human_updates</code> at safe checkpoints.</p><div className="form-actions">{!token?<button type="button" className="button button-primary" disabled={busy} onClick={connect}><ShieldCheck size={16}/>{busy?"Creating…":"Create connection"}</button>:<><button type="button" className="button button-secondary" onClick={()=>navigator.clipboard.writeText(config)}><Copy size={16}/>Copy MCP configuration</button><button type="button" className="button button-quiet danger" disabled={busy} onClick={disconnect}>Revoke connection</button></>}</div>{token&&<textarea className="connection-config" value={config} readOnly aria-label="MCP configuration"/>}<div className="message-box"><label>Send your agent an update<textarea value={message} onChange={e=>setMessage(e.target.value)} placeholder="For the homepage, use the blue direction and keep the layout minimal." maxLength={4000}/></label><button type="button" className="button button-secondary" disabled={busy||!message.trim()} onClick={send}><Send size={15}/>Send update</button></div>{notice&&<p className="connection-notice"><Check size={15}/>{notice}</p>}{error&&<p className="form-message">{error}</p>}</div></section>;
}
