"use client";
import { useState } from "react";
import { useRouter } from "next/navigation";
type Agent = { id: string; name: string; description: string | null; system_prompt: string | null; status: string };
export function AgentForm({ agent }: { agent?: Agent }) {
  const router = useRouter(); const [loading,setLoading]=useState(false); const [error,setError]=useState<string>();
  const [name,setName]=useState(agent?.name ?? ""); const [description,setDescription]=useState(agent?.description ?? ""); const [systemPrompt,setSystemPrompt]=useState(agent?.system_prompt ?? ""); const [status,setStatus]=useState(agent?.status ?? "active");
  async function submit(e: React.FormEvent) { e.preventDefault(); setLoading(true); setError(undefined); const response=await fetch(agent?`/api/agents/${agent.id}`:"/api/agents",{method:agent?"PATCH":"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({name,description,systemPrompt,status})}); const result=await response.json(); setLoading(false); if(!response.ok){setError(result.error||"Could not save agent.");return;} router.push(agent?"/agents":"/agents");router.refresh(); }
  async function archive(){if(!agent||!confirm("Archive this agent? You can no longer make calls from it."))return;setLoading(true);const r=await fetch(`/api/agents/${agent.id}`,{method:"DELETE"});setLoading(false);if(!r.ok){setError("Could not archive agent.");return;}router.push("/agents");router.refresh();}
  return <form className="panel form-panel" onSubmit={submit}><div className="form-grid"><label>Agent name<input required value={name} onChange={e=>setName(e.target.value)} placeholder="Appointment Assistant" maxLength={100}/></label><label>Status<select value={status} onChange={e=>setStatus(e.target.value)}><option value="active">Active</option><option value="paused">Paused</option>{agent&&<option value="archived">Archived</option>}</select></label></div><label>Description<textarea value={description} onChange={e=>setDescription(e.target.value)} placeholder="Calls customers to confirm appointments." maxLength={600}/></label><label>Instructions / system prompt<textarea className="prompt-input" value={systemPrompt} onChange={e=>setSystemPrompt(e.target.value)} placeholder="You are calling on behalf of…" maxLength={6000}/></label>{error&&<p className="form-message">{error}</p>}<div className="form-actions"><button className="button button-primary" disabled={loading}>{loading?"Saving…":agent?"Save changes":"Create agent"}</button>{agent&&<button type="button" className="button button-quiet danger" onClick={archive} disabled={loading}>Archive agent</button>}</div></form>;
}
