export const connectionHosts = [
  "codex", "claude-code", "gemini-cli", "kiro", "antigravity", "chatgpt-web", "generic",
] as const;
export type ConnectionHost = typeof connectionHosts[number];
export type ConnectionSetup = { label: string; support: "supported" | "pending"; location: string; verify: string; config: (endpoint: string, token: string) => string; };

const genericConfig = (endpoint: string, token: string) => JSON.stringify({ mcpServers: { callyouragent: { url: endpoint, headers: { Authorization: `Bearer ${token}` } } } }, null, 2);

export const connectionSetups: Record<ConnectionHost, ConnectionSetup> = {
  codex: { label: "Codex CLI / IDE", support: "supported", location: "Run the generated command in the same shell where you run Codex. It registers a remote Streamable HTTP MCP server without putting the token in your repository.", verify: "Restart Codex, then run /mcp and confirm callyouragent is connected.", config: (endpoint, token) => `$env:CALLYOURAGENT_TOKEN = \"${token}\"\ncodex mcp add callyouragent --url \"${endpoint}\" --bearer-token-env-var CALLYOURAGENT_TOKEN\ncodex mcp list` },
  "claude-code": { label: "Claude Code", support: "supported", location: "Create or update .mcp.json in the project root. Keep it out of source control because this configuration contains a private connection token.", verify: "Restart Claude Code and use /mcp to confirm callyouragent is connected.", config: (endpoint, token) => JSON.stringify({ mcpServers: { callyouragent: { type: "http", url: endpoint, headers: { Authorization: `Bearer ${token}` } } } }, null, 2) },
  "gemini-cli": { label: "Gemini CLI", support: "supported", location: "Add this entry to ~/.gemini/settings.json or the project’s .gemini/settings.json. Do not commit the private token.", verify: "Restart Gemini CLI, then run /mcp list and confirm callyouragent is connected.", config: (endpoint, token) => JSON.stringify({ mcpServers: { callyouragent: { httpUrl: endpoint, headers: { Authorization: `Bearer ${token}` } } } }, null, 2) },
  kiro: { label: "Kiro", support: "supported", location: "Press Ctrl+Shift+P → Kiro: Open workspace MCP config (JSON), then add this server to the mcpServers object.", verify: "Save the configuration and open Kiro’s MCP panel. CallYourAgent must show as connected before work starts.", config: genericConfig },
  antigravity: { label: "Antigravity", support: "supported", location: "Open Agent panel → … → MCP Servers → Manage MCP Servers → View raw config, then add this server. Its remote key is serverUrl.", verify: "Save the raw MCP configuration and confirm CallYourAgent reconnects in the MCP Servers panel.", config: (endpoint, token) => JSON.stringify({ mcpServers: { callyouragent: { serverUrl: endpoint, headers: { Authorization: `Bearer ${token}` } } } }, null, 2) },
  "chatgpt-web": { label: "ChatGPT web / Work", support: "pending", location: "This hosted product cannot be connected with a pasted bearer token. It needs a published ChatGPT app plus per-user OAuth, which this release does not provide.", verify: "Use one of the supported local MCP clients above or a generic compatible IDE today.", config: () => "ChatGPT web / Work setup is not available in this release. Do not paste a CallYourAgent token into ChatGPT web." },
  generic: { label: "Any other IDE / custom agent", support: "supported", location: "Use a client that supports remote Streamable HTTP MCP servers and static Authorization headers. Add this object to its MCP configuration, adapting url to httpUrl or serverUrl only if that client documents a different key.", verify: "Use the client’s MCP inspector to list tools. It must discover request_phone_call, get_call_status, and pull_human_updates.", config: genericConfig },
};

export function connectionPrompt(host: ConnectionHost, endpoint: string, token?: string) {
  const setup = connectionSetups[host]; const secret = token ? `\n\nPrivate connection configuration:\n${setup.config(endpoint, token)}` : "";
  return `Set up CallYourAgent for ${setup.label}. ${setup.location}\n\nEndpoint: ${endpoint}\nVerification: ${setup.verify}${secret}\n\nAfter the MCP connection is confirmed, use request_phone_call only when an owner-authorized decision, confirmation, or alert genuinely needs a phone call. The number must be E.164. Use get_call_status after starting a call. At safe checkpoints call pull_human_updates and apply returned instructions. Never ask for a CALL-E API key, never expose this connection token, and never claim that an owner update interrupted an in-progress response.`;
}
