/**
 * Browser-local connection guide for a self-hosted CallYourAgent instance.
 * It intentionally never posts phone numbers or bearer tokens: the user copies
 * the generated deployment and MCP configuration into their own trusted setup.
 */
export function connectionKitHtml(): string {
  return `<!doctype html>
<html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1">
<title>Connect an agent · CallYourAgent</title><style>
:root{font-family:Inter,ui-sans-serif,system-ui,sans-serif;color:#eaf2ff;background:#07111f}*{box-sizing:border-box}body{margin:0;background:radial-gradient(circle at top,#132d50,#07111f 48%);min-height:100vh}main{width:min(920px,94vw);margin:auto;padding:52px 0}h1{font-size:clamp(32px,6vw,54px);letter-spacing:-.05em;margin:5px 0}.tag{color:#90b7ff;font-weight:700;font-size:12px;text-transform:uppercase;letter-spacing:.13em}.muted{color:#a8b7ca;line-height:1.55}.grid{display:grid;grid-template-columns:1fr 1fr;gap:18px;margin-top:28px}.card{background:#0b1b2fdd;border:1px solid #29486d;border-radius:18px;padding:22px}label{display:block;font-size:13px;color:#b7c7dd;margin:14px 0 6px}input,select,textarea{width:100%;padding:11px;border-radius:10px;background:#081727;color:#edf4ff;border:1px solid #345577;font:inherit}textarea{min-height:150px;resize:vertical}button{border:0;border-radius:10px;padding:11px 14px;background:#3679ef;color:white;font-weight:700;cursor:pointer;margin-top:14px}.wide{grid-column:1/-1}@media(max-width:720px){.grid{grid-template-columns:1fr}}code{color:#b9d5ff}.notice{border-left:3px solid #74d7b8;padding-left:12px;color:#c2d7ec}
</style></head><body><main>
<div class="tag">CallYourAgent connection kit</div><h1>Connect your phone to your agent.</h1>
<p class="muted">Your agent continues normal work. When one scope needs your judgment, it calls you; your answer becomes durable state at the next safe checkpoint. You can request a callback to hear progress and queue steering.</p>
<div class="grid"><section class="card"><h2>1. Your control plane</h2>
<label>Public HTTPS control-plane URL</label><input id="base" placeholder="https://cya.example.com">
<label>Your phone number (E.164)</label><input id="phone" placeholder="+919920090093" inputmode="tel">
<label>Agent host</label><select id="host"><option value="codex">Codex</option><option value="claude">Claude Code</option><option value="generic">Generic stdio MCP host</option></select>
<label>Agent bearer token</label><input id="agentToken" type="password" autocomplete="off" placeholder="generated agent token">
<label>Owner bearer token</label><input id="ownerToken" type="password" autocomplete="off" placeholder="generated owner token">
<button id="generate">Generate connection instructions</button>
<p class="notice">This page does not submit or store your phone number or tokens. Keep CALL-E and deployment secrets server-side.</p></section>
<section class="card"><h2>2. Deploy configuration</h2><p class="muted">Create the credentials bundle on the server with <code>npm run credentials:generate</code>, then paste its agent and owner token values above.</p><textarea id="env" readonly placeholder="Your server environment will appear here."></textarea></section>
<section class="card wide"><h2>3. Add the MCP connector</h2><p class="muted">Give only the agent token to the agent host. It can register runs, ask for branch-scoped decisions, read decisions, and checkpoint instructions. It never receives your CALL-E API key, owner token, or provider-reconciliation token.</p><textarea id="mcp" readonly placeholder="Your MCP configuration will appear here."></textarea>
<h2>4. Give the agent this operating instruction</h2><textarea id="prompt" readonly placeholder="The safe-checkpoint instruction will appear here."></textarea></section></div>
</main><script>(()=>{const $=id=>document.getElementById(id);const output=()=>{const base=$('base').value.trim().replace(/\/$/,'');const phone=$('phone').value.trim();const agent=$('agentToken').value.trim();const owner=$('ownerToken').value.trim();const host=$('host').value;const url=base||'https://cya.example.com';$('env').value=['CYA_CALL_PROVIDER=calle','CYA_OWNER_PHONE='+ (phone||'<YOUR_E164_PHONE>'),'CYA_PUBLIC_BASE_URL='+url,'CALLE_API_KEY=<STORE_IN_SERVER_SECRET_MANAGER>','CYA_CALLE_WEBHOOK_TOKEN=<GENERATE_HIGH_ENTROPY_SECRET>','CYA_API_CREDENTIALS_JSON=<OUTPUT_OF_npm_run_credentials:generate>'].join('\n');const env={CYA_BASE_URL:url,CYA_API_TOKEN:agent||'<AGENT_TOKEN>'};const config={mcpServers:{callyouragent:{command:'node',args:['/absolute/path/to/CallYourAgent/dist/src/mcp-server.js'],env}}};$('mcp').value=host==='claude'?'claude mcp add callyouragent --env CYA_BASE_URL='+url+' --env CYA_API_TOKEN='+(agent||'<AGENT_TOKEN>')+' -- node /absolute/path/to/CallYourAgent/dist/src/mcp-server.js\n\n'+JSON.stringify(config,null,2):JSON.stringify(config,null,2);$('prompt').value='Use CallYourAgent for genuine human judgment only. Register this agent and start a run. Report compact status as work changes. If one scope needs an owner decision, call request_owner_decision with that scopeId, blocking=true only when that scope cannot safely continue, and a stable idempotencyKey. Continue unrelated scopes. At explicit safe checkpoints call checkpoint with consume=false, incorporate queued instructions, then acknowledge exactly the instruction ids you used. Never claim an in-flight generation can be interrupted. The owner can request callbacks through the separate owner surface using their owner token.'; if(owner){$('mcp').value+='\n\nOwner console: '+url+'/operator — enter the owner token only in the browser.'}};$('generate').addEventListener('click',output);})();</script></body></html>`;
}
